In [10]:
# %pip install pyswip
# %pip install pandas
from pyswip import Prolog
import pandas as pd
import csv

In [11]:
# Clear existing facts to avoid duplicates

prolog = Prolog()
prolog.retractall("my_destination(_)")
prolog.retractall("country(_,_)")
prolog.retractall("region(_,_)")
prolog.retractall("climate(_,_)")
prolog.retractall("budget(_,_)")
prolog.retractall("activity(_,_)")
prolog.retractall("demographic(_,_)")
prolog.retractall("duration(_,_)")
prolog.retractall("cuisine(_,_)")
prolog.retractall("history(_,_)")
prolog.retractall("natural_wonder(_,_)")
prolog.retractall("accommodation(_,_)")
prolog.retractall("language(_,_)")
prolog.retractall("is_country(_)")
prolog.retractall("is_region(_)")
prolog.retractall("is_climate(_)")
prolog.retractall("is_budget(_)")
prolog.retractall("is_activity(_)")
prolog.retractall("is_demographic(_)")
prolog.retractall("is_duration(_)")
prolog.retractall("is_cuisine(_)")
prolog.retractall("is_history(_)")
prolog.retractall("is_natural_wonder(_)")
prolog.retractall("is_accommodation(_)")
prolog.retractall("is_language(_)")
prolog.retractall("connected(_,_)")

In [12]:
# Read data from CSV and assert facts into Prolog
with open('../../data/Destinations.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)

    for row in reader:
        destination = row['Destinations']

        prolog.assertz(f"my_destination('{destination}')")
        prolog.assertz(f"country('{destination}', '{row['country']}')")
        prolog.assertz(f"region('{destination}', '{row['region']}')")
        prolog.assertz(f"climate('{destination}', '{row['Climate']}')")
        prolog.assertz(f"budget('{destination}', '{row['Budget']}')")
        prolog.assertz(f"activity('{destination}', '{row['Activity']}')")
        prolog.assertz(f"demographic('{destination}', '{row['Demographics']}')")
        prolog.assertz(f"duration('{destination}', '{row['Duration']}')")
        prolog.assertz(f"cuisine('{destination}', '{row['Cuisine']}')")
        prolog.assertz(f"history('{destination}', '{row['History']}')")
        prolog.assertz(f"natural_wonder('{destination}', '{row['Natural Wonder']}')")
        prolog.assertz(f"accommodation('{destination}', '{row['Accommodation']}')")
        prolog.assertz(f"language('{destination}', '{row['Language']}')")

In [13]:
data = pd.read_csv('../../data/Destinations.csv')
for country in set(data['country'].values):
    prolog.assertz(f"is_country('{country}')")

for region in set(data['region'].values):
    prolog.assertz(f"is_region('{region}')")

for climate in set(data['Climate'].values):
    prolog.assertz(f"is_climate('{climate}')")

for budget in set(data['Budget'].values):
    prolog.assertz(f"is_budget('{budget}')")

for activity in set(data['Activity'].values):
    prolog.assertz(f"is_activity('{activity}')")

for demographic in set(data['Demographics'].values):
    prolog.assertz(f"is_demographic('{demographic}')")

for duration in set(data['Duration'].values):
    prolog.assertz(f"is_duration('{duration}')")

for cuisine in set(data['Cuisine'].values):
    prolog.assertz(f"is_cuisine('{cuisine}')")

for history in set(data['History'].values):
    prolog.assertz(f"is_history('{history}')")

for natural_wonder in set(data['Natural Wonder'].values):
    prolog.assertz(f"is_natural_wonder('{natural_wonder}')")

for accommodation in set(data['Accommodation'].values):
    prolog.assertz(f"is_accommodation('{accommodation}')")

for language in set(data['Language'].values):
    prolog.assertz(f"is_language('{language}')")

In [14]:
adj_matrix = pd.read_csv('..//..//data//Adjacency_matrix.csv')
adj_matrix

,Destinations,Tokyo,Ottawa,Mexico City,Rome,Brasilia,Canberra,New Delhi,Pretoria,Madrid,...,Bursa,Munich,Hamburg,Frankfurt,Alexandria,Luxor,Aswan,Christchurch,Queenstown,Rotorua
0,Tokyo,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,1
1,Ottawa,1,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,0,0
2,Mexico City,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
3,Rome,1,0,0,0,1,1,1,0,0,...,1,0,1,0,0,0,0,0,1,0
4,Brasilia,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Luxor,1,1,0,0,0,0,0,0,1,...,0,0,1,0,0,1,0,0,1,0
98,Aswan,1,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
99,Christchurch,1,0,0,1,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,1
100,Queenstown,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,1,1,0,0,0
101,Rotorua,0,0,0,0,0,1,0,0,1,...,0,0,1,0,0,0,0,0,0,1

In [72]:
for i in range(1, len(adj_matrix.columns)):
    for j in range(i + 1, len(adj_matrix.columns)):
        #if adj_matrix.iloc[i, j] == 1:
            # print('origin:', adj_matrix.iloc[i])
            print('destination: ', adj_matrix.iloc[:,j])

#for origin_index in range(1, len(adj_matrix.columns)):
#    for dest_index in range(1, len(adj_matrix.columns)):
#        if adj_matrix.iloc[dest_index, origin_index] == 1 and adj_matrix.columns[origin_index] != adj_matrix.columns[dest_index]:
#            print(adj_matrix.iloc[dest_index, origin_index])
#            print(origin_index, dest_index)
#            prolog.assertz(f"connected('{adj_matrix.columns[origin_index]}', '{adj_matrix.columns[dest_index]}')")
#            prolog.assertz(f"connected('{adj_matrix.columns[dest_index]}', '{adj_matrix.columns[origin_index]}')")
#            print('origin: ', adj_matrix.columns[origin_index])
#            print('destination: ', adj_matrix.columns[dest_index])
#list(prolog.query(f"connected('Tokyo', 'Ottawa')"))
#connected2 = list(prolog.query(f"connected('Tokyo', X), connected(X,'Mexico City')"))
#connected2

destination:  0      0
1      0
2      1
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Ottawa, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    0
Name: Mexico City, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     0
99     1
100    0
101    0
Name: Rome, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Brasilia, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    0
101    1
Name: Canberra, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     0
98     1
99     0
100    1
101    0
Name: New Delhi, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Pretoria, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    1
Name: Madrid, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     1
100    0
101    0
Name: Moscow, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    1
Name: Berlin, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    1
Name: Bangkok, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      1
4      0
      ..
97     0
98     0
99     1
100    0
101    0
Name: Stockholm, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      1
4      1
      ..
97     0
98     1
99     0
100    0
101    0
Name: Cairo, Length: 102, dtype: int64
destination:  0      1
1      1
2      0
3      0
4      1
      ..
97     0
98     0
99     0
100    1
101    0
Name: Wellington, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Ankara, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    0
101    0
Name: Buenos Aires, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     0
99     1
100    0
101    0
Name: Kathmandu, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Athens, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    1
101    0
Name: Nairobi, Length: 102, dtype: int64
destination:  0      1
1      0
2      1
3      1
4      1
      ..
97     0
98     0
99     0
100    0
101    0
Name: Lisbon, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    1
101    0
Name: Oslo, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Jakarta, Length: 102, dtype: int64
destination:  0      1
1      0
2      1
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    1
Name: Hanoi, Length: 102, dtype: int64
destination:  0      1
1      1
2      0
3      0
4      0
      ..
97     1
98     1
99     0
100    0
101    1
Name: Dublin, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Beijing, Length: 102, dtype: int64
destination:  0      1
1      1
2      1
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    0
Name: Paris, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      1
      ..
97     0
98     0
99     0
100    0
101    0
Name: Santiago, Length: 102, dtype: int64
destination:  0      1
1      0
2      1
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    0
Name: Rabat, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     0
99     1
100    0
101    0
Name: Singapore, Length: 102, dtype: int64
destination:  0      0
1      1
2      1
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Lima, Length: 102, dtype: int64
destination:  0      1
1      1
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Helsinki, Length: 102, dtype: int64
destination:  0      1
1      0
2      1
3      0
4      1
      ..
97     0
98     0
99     0
100    0
101    0
Name: Prague, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      0
4      0
      ..
97     0
98     1
99     0
100    0
101    0
Name: Manila, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     1
98     0
99     0
100    1
101    0
Name: Brussels, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Kuala Lumpur, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Amsterdam, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     0
99     0
100    1
101    0
Name: Washington D.C., Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      1
      ..
97     0
98     1
99     0
100    1
101    0
Name: London, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Seoul, Length: 102, dtype: int64
destination:  0      1
1      1
2      0
3      1
4      0
      ..
97     0
98     1
99     0
100    0
101    1
Name: Bogota, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Warsaw, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     1
98     1
99     0
100    0
101    0
Name: Jerusalem, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     1
98     0
99     1
100    0
101    0
Name: Kyiv, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     0
99     0
100    1
101    0
Name: Vienna, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Copenhagen, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     1
98     0
99     0
100    0
101    1
Name: Dhaka, Length: 102, dtype: int64
destination:  0      0
1      1
2      1
3      0
4      0
      ..
97     0
98     1
99     0
100    0
101    1
Name: Montevideo, Length: 102, dtype: int64
destination:  0      0
1      1
2      1
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Bern, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    0
101    0
Name: Islamabad, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    0
Name: Budapest, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     0
99     1
100    0
101    1
Name: Zagreb, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      1
      ..
97     0
98     0
99     1
100    0
101    0
Name: Colombo, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      1
      ..
97     0
98     0
99     0
100    0
101    1
Name: Tehran, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     1
98     1
99     0
100    0
101    0
Name: Bratislava, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      1
4      1
      ..
97     0
98     0
99     1
100    1
101    1
Name: Cancun, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    1
101    0
Name: Venice, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Florence, Length: 102, dtype: int64
destination:  0      1
1      1
2      0
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    1
Name: Milan, Length: 102, dtype: int64
destination:  0      0
1      1
2      1
3      1
4      1
      ..
97     0
98     0
99     1
100    0
101    1
Name: Saint Petersburg, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      0
4      0
      ..
97     0
98     0
99     0
100    1
101    0
Name: Vladivostok, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    0
Name: New York City, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      0
4      1
      ..
97     0
98     0
99     1
100    1
101    1
Name: Los Angeles, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Chicago, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    1
101    1
Name: Miami, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Shiraz, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Isfahan, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    0
Name: Mashhad, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     0
98     1
99     0
100    0
101    0
Name: Tabriz, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      0
4      0
      ..
97     1
98     1
99     0
100    0
101    0
Name: Yazd, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Shanghai, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     1
98     0
99     1
100    0
101    0
Name: Guangzhou, Length: 102, dtype: int64
destination:  0      0
1      1
2      1
3      0
4      1
      ..
97     1
98     0
99     0
100    0
101    1
Name: Chengdu, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Xian, Length: 102, dtype: int64
destination:  0      0
1      1
2      1
3      0
4      0
      ..
97     0
98     0
99     0
100    1
101    0
Name: Bergen, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     1
98     0
99     0
100    1
101    0
Name: Tromsø, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Marseille, Length: 102, dtype: int64
destination:  0      1
1      0
2      1
3      1
4      0
      ..
97     1
98     0
99     1
100    0
101    1
Name: Lyon, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     1
99     1
100    0
101    0
Name: Sentosa, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      0
4      0
      ..
97     0
98     0
99     0
100    1
101    0
Name: Marina Bay, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     0
98     1
99     0
100    0
101    0
Name: Cusco, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    1
Name: Arequipa, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    1
Name: Busan, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      1
4      0
      ..
97     0
98     1
99     0
100    0
101    0
Name: Incheon, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      0
4      1
      ..
97     1
98     1
99     0
100    0
101    0
Name: Medellin, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    0
Name: Cali, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    0
Name: Lahore, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      1
4      0
      ..
97     0
98     0
99     1
100    1
101    1
Name: Karachi, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    0
101    1
Name: Zurich, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    1
Name: Geneva, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    1
101    1
Name: Izmir, Length: 102, dtype: int64
destination:  0      1
1      0
2      1
3      0
4      1
      ..
97     0
98     0
99     0
100    0
101    0
Name: Antalya, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      1
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Bursa, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    0
Name: Munich, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     1
98     0
99     1
100    0
101    1
Name: Hamburg, Length: 102, dtype: int64
destination:  0      1
1      1
2      0
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    0
Name: Frankfurt, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Alexandria, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     1
98     0
99     0
100    1
101    0
Name: Luxor, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    0
Name: Aswan, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Christchurch, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      1
4      1
      ..
97     1
98     0
99     1
100    0
101    0
Name: Queenstown, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    1
Name: Rotorua, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    0
Name: Mexico City, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     0
99     1
100    0
101    0
Name: Rome, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Brasilia, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    0
101    1
Name: Canberra, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     0
98     1
99     0
100    1
101    0
Name: New Delhi, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Pretoria, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    1
Name: Madrid, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     1
100    0
101    0
Name: Moscow, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    1
Name: Berlin, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    1
Name: Bangkok, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      1
4      0
      ..
97     0
98     0
99     1
100    0
101    0
Name: Stockholm, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      1
4      1
      ..
97     0
98     1
99     0
100    0
101    0
Name: Cairo, Length: 102, dtype: int64
destination:  0      1
1      1
2      0
3      0
4      1
      ..
97     0
98     0
99     0
100    1
101    0
Name: Wellington, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      1
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Ankara, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     0
98     1
99     0
100    0
101    0
Name: Buenos Aires, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     0
99     1
100    0
101    0
Name: Kathmandu, Length: 102, dtype: int64
destination:  0      0
1      0
2      1
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    0
Name: Athens, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      0
      ..
97     0
98     0
99     0
100    1
101    0
Name: Nairobi, Length: 102, dtype: int64
destination:  0      1
1      0
2      1
3      1
4      1
      ..
97     0
98     0
99     0
100    0
101    0
Name: Lisbon, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      1
4      0
      ..
97     0
98     0
99     0
100    1
101    0
Name: Oslo, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Jakarta, Length: 102, dtype: int64
destination:  0      1
1      0
2      1
3      0
4      0
      ..
97     0
98     0
99     0
100    0
101    1
Name: Hanoi, Length: 102, dtype: int64
destination:  0      1
1      1
2      0
3      0
4      0
      ..
97     1
98     1
99     0
100    0
101    1
Name: Dublin, Length: 102, dtype: int64
destination:  0      1
1      0
2      0
3      0
4      0
      ..
97     1
98     0
99     0
100    0
101    0
Name: Beijing, Length: 102, dtype: int64
destination:  0      1
1      1
2      1
3      0
4      0
      ..
97     0
98     0
99     1
100    0
101    0
Name: Paris, Length: 102, dtype: int64
destination:  0      0
1      1
2      0
3      0
4      1
      ..
97     0
98     0
99     0
100    0
101    0
Name: Santiago, Length: 102, dtype: int64
destination:  0      1
1      0
2      1
3      0
4      0
      ..
97     0
98     1
99     0
100    1
101    0
Name: Rabat, Length: 102, dtype: int64
destination:  0      0
1      0
2      0
3      0
4      1
      ..
97     0
98     0
99     1
100    0
101    0
Name: Singapore, Length: 102, dtype: int64
destination:  0      0
1      1
2      1
3      0
4      0
      ..
97     0
98     0
99     0
100    0

In [31]:
import re
import string

def clean_text(text):
    text = re.sub('\[.*?\]', ' ', text)
    text = re.sub('<.*?>+', ' ', text)
    text = re.sub('\n', ' ', text)
    text = re.sub('\w*\d\w*', ' ', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
    return text

yarru_chi_gof = input().split()
cleaned_chizi_ke_goft = [word.replace('_', ' ') if '_' in word else word for word in yarru_chi_gof]

print(cleaned_chizi_ke_goft)
capitalized_cleaned_chizi_ke_goft = [word.title() for word in cleaned_chizi_ke_goft]
print(capitalized_cleaned_chizi_ke_goft) 

dict = {'country': [], 'region':[], 'climate':[], 'budget':[], 'activity': [], 'demographic': [],
        'duration': [], 'cuisine': [], 'history': [], 'natural_wonder': [], 'accommodation': [],
        'language': []}

for chiz in capitalized_cleaned_chizi_ke_goft:
    chiz = clean_text
    if list(prolog.query(f"is_country('{chiz}')")):
        dict['country'].append(chiz)
    if list(prolog.query(f"is_region('{chiz}')")):
        dict['region'].append(chiz)
    if list(prolog.query(f"is_climate('{chiz}')")):
        dict['climate'].append(chiz)
    if list(prolog.query(f"is_budget('{chiz}')")):
        dict['budget'].append(chiz)
    if list(prolog.query(f"is_activity('{chiz}')")):
        dict['activity'].append(chiz)
    if list(prolog.query(f"is_demographic('{chiz}')")):
        dict['demographic'].append(chiz)
    if list(prolog.query(f"is_duration('{chiz}')")):
        dict['duration'].append(chiz)
    if list(prolog.query(f"is_cuisine('{chiz}')")):
        dict['cuisine'].append(chiz)
    if list(prolog.query(f"is_history('{chiz}')")):
        dict['history'].append(chiz)
    if list(prolog.query(f"is_natural_wonder('{chiz}')")):
        dict['natural_wonder'].append(chiz)
    if list(prolog.query(f"is_accommodation('{chiz}')")):
        dict['accommodation'].append(chiz)
    if list(prolog.query(f"is_language('{chiz}')")):
        dict['language'].append(chiz)

dict

<>:5: SyntaxWarning: invalid escape sequence '\['
<>:8: SyntaxWarning: invalid escape sequence '\w'
<>:5: SyntaxWarning: invalid escape sequence '\['
<>:8: SyntaxWarning: invalid escape sequence '\w'
C:\Users\RSKALA\AppData\Local\Temp\ipykernel_17048\4083047542.py:5: SyntaxWarning: invalid escape sequence '\['
  text = re.sub('\[.*?\]', ' ', text)
C:\Users\RSKALA\AppData\Local\Temp\ipykernel_17048\4083047542.py:8: SyntaxWarning: invalid escape sequence '\w'
  text = re.sub('\w*\d\w*', ' ', text)

 latin_american with low budget.

['latin american', 'with', 'low', 'budget.']
['Latin American', 'With', 'Low', 'Budget.']
Latin American
With
Low
Budget

{'country': [],
 'region': [],
 'climate': [],
 'budget': ['Low'],
 'activity': [],
 'demographic': [],
 'duration': [],
 'cuisine': ['Latin American'],
 'history': [],
 'natural_wonder': [],
 'accommodation': [],
 'language': []}

In [32]:
keys = list(dict.keys())
citys = list(prolog.query("my_destination(X)"))
list_of_city = [item['X'] for item in citys] 

for key in keys:
    for value in dict[key]:
        if dict[key]:
            featured_list = [item['X'] for item in list(prolog.query(f"{key}(X, '{value}')"))]
        list_of_city = list(set(list_of_city).intersection(featured_list))
list_of_city

['Brasilia',
 'Arequipa',
 'Mexico City',
 'Cusco',
 'Medellin',
 'Cali',
 'Lima',
 'Buenos Aires',
 'Bogota']

In [ ]:
def permutation_path(lst):
	if len(lst) == 0:
		return []

	if len(lst) == 1:
		return [lst]

	l = []

	for i in range(len(lst)):
    	origin = lst[i]
    	remLst = lst[:i] + lst[i+1:]
    
    	for dest in permutation(remLst):
            if list(prolog.query(f"connected('{origin}','{dest}')")):
        		l.append([origin] + dest)
            else:
                connected2 = list(prolog.query(f"connected('{origin}', X), connected(X,'{dest}')")
	return l

In [ ]:
if len(list_of_city) <= 0:
    print("We could't find any destinations with given information. please remove some conditions")

elif len(list_of_city) > 5:
    print("Information is not enough for specific destinations.")

else:
    permutation_path(list_of_city)